### ISSUE TITLE
Hiding host’s telephone number on HousingResources list

### ISSUE THREAD

**Issue by raphaelsolarski** [ukrainski-dom/housing-app#7]
* During selecting host for submission host's telephone number should be only visible after clicking “Dzwonię” (eng. I’m calling) button.
* (but HousingResources should be still searchable by host number).

Motivation: sometimes users forget to mark outcome after call and the same hosts are called multiple times.

**Comment by bartoszkp** [comment]
Sorry, seems I'm late and this has already been implemented... :-)
